# Generated by Django 6.0.3 on 2026-03-21 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Pets', 'Pets'), ('Documents', 'Documents'), ('Bags', 'Bags'), ('Wallet', 'Wallet')], max_length=20)),
                ('item_type', models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='items/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('secret_question', models.TextField()),
                ('secret_answer', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MATCHED', 'Matched'), ('RETURNED', 'Returned')], default='ACTIVE', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
