# Generated by Django 6.0.3 on 2026-03-22 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color_vector',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='labels',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expected_matches', to='items.item')),
                ('matched_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_to', to='items.item')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('item', 'matched_item')},
            },
        ),
    ]
