# Generated by Django 6.0.3 on 2026-03-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_color_vector_item_image_hash_item_labels_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
