# Generated by Django 6.0.3 on 2026-03-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='color_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='match',
            name='label_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='match',
            name='location_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='match',
            name='text_score',
            field=models.FloatField(default=0.0),
        ),
    ]
