# Generated by Django 6.0.3 on 2026-05-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_remove_item_secret_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label_scores',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
