# Generated by Django 6.0.3 on 2026-05-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_add_label_scores_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_weight', models.FloatField(default=0.25, help_text='Weight for color similarity (0.0 to 1.0)')),
                ('label_weight', models.FloatField(default=0.35, help_text='Weight for MobileNetV2 label similarity (0.0 to 1.0)')),
                ('location_weight', models.FloatField(default=0.2, help_text='Weight for location proximity similarity (0.0 to 1.0)')),
                ('text_weight', models.FloatField(default=0.2, help_text='Weight for title & description text similarity (0.0 to 1.0)')),
                ('threshold', models.FloatField(default=0.7, help_text='Minimum aggregate score threshold (0.0 to 1.0) to register a match')),
            ],
            options={
                'verbose_name': 'Matching Configuration',
                'verbose_name_plural': 'Matching Configurations',
            },
        ),
    ]
