# Generated by Django 6.0.3 on 2026-05-28 09:38

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_matchingconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundPhone',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.item')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('os_type', models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android')], max_length=20)),
                ('imei', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('imei_source', models.CharField(choices=[('emergency_dialer', 'Emergency Dialer'), ('sim_tray', 'SIM Tray'), ('back_of_phone', 'Back of Phone'), ('not_found', 'Not Found')], default='not_found', max_length=30)),
                ('is_device_locked', models.BooleanField(default=True)),
                ('lock_screen_message', models.CharField(blank=True, max_length=255, null=True)),
                ('is_factory_reset', models.BooleanField(default=False)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('screen_cracked', 'Screen Cracked'), ('damaged', 'Damaged')], max_length=20)),
            ],
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='LostPhone',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.item')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('storage_capacity', models.CharField(max_length=20)),
                ('os_type', models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android')], max_length=20)),
                ('imei', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('screen_cracked', 'Screen Cracked'), ('damaged', 'Damaged')], max_length=20)),
                ('lock_screen_message', models.CharField(blank=True, max_length=255, null=True)),
                ('reward_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            bases=('items.item',),
        ),
    ]
