# Generated by Django 6.0.3

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_foundphone_lostphone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LostPhone',
            new_name='LostElectronic',
        ),
        migrations.RenameModel(
            old_name='FoundPhone',
            new_name='FoundElectronic',
        ),
        migrations.RenameField(
            model_name='lostelectronic',
            old_name='imei',
            new_name='imei_or_serial',
        ),
        migrations.RenameField(
            model_name='foundelectronic',
            old_name='imei',
            new_name='imei_or_serial',
        ),
        migrations.RenameField(
            model_name='foundelectronic',
            old_name='imei_source',
            new_name='imei_or_serial_source',
        ),
        migrations.AddField(
            model_name='lostelectronic',
            name='electronic_type',
            field=models.CharField(choices=[('mobile_phone', 'Mobile Phone'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('earbuds', 'Earbuds'), ('smartwatch', 'Smartwatch'), ('camera', 'Camera'), ('accessories', 'Accessories')], default='mobile_phone', max_length=50),
        ),
        migrations.AddField(
            model_name='foundelectronic',
            name='electronic_type',
            field=models.CharField(choices=[('mobile_phone', 'Mobile Phone'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('earbuds', 'Earbuds'), ('smartwatch', 'Smartwatch'), ('camera', 'Camera'), ('accessories', 'Accessories')], default='mobile_phone', max_length=50),
        ),
        migrations.AlterField(
            model_name='lostelectronic',
            name='storage_capacity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lostelectronic',
            name='os_type',
            field=models.CharField(blank=True, choices=[('iOS', 'iOS'), ('Android', 'Android')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='foundelectronic',
            name='os_type',
            field=models.CharField(blank=True, choices=[('iOS', 'iOS'), ('Android', 'Android')], max_length=20, null=True),
        ),
    ]
