# Generated by Django 6.0.3 on 2026-05-31 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_rename_phone_to_electronic'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
            ],
            options={
                'verbose_name': 'Found Item',
                'verbose_name_plural': 'Found Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('items.item',),
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
            ],
            options={
                'verbose_name': 'Lost Item',
                'verbose_name_plural': 'Lost Items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('items.item',),
        ),
    ]
